if: branch = master

dist: xenial
language: go
go:
  - 1.11.x

addons:
  ssh_known_hosts: johnjago.com

script:
  - mkdir -p dist/blog/
  # Build the Hugo blog and move output to dist/blog/ at root
  - cd src/blog/
  - ../../bin/hugo && mv public/* ../../dist/blog/ && cd ..
  # Insert hash into CSS filename for cache busting
  - ./build.sh
  # Move project site into dist/
  # favicon.png is the full-size version of favicon-32x32.png
  - rsync -av --exclude=blog/ --exclude=favicon.png --exclude=style.css . ../dist/
  - cd ..

before_deploy:
  - openssl aes-256-cbc -K $encrypted_829f045482e5_key -iv $encrypted_829f045482e5_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  skip_cleanup: true
  provider: script
  script: rsync -azvP --omit-dir-times --delete --exclude=/deformat --exclude=/musearch dist/ $USER@johnjago.com:$WWW/
